// Generated by script/export-abis.sh. Do not edit.
export const JoinRequestsAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "payroll",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "I_PAYROLL",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IDayzePayroll"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_PENDING",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "cancelRequest",
    "inputs": [
      {
        "name": "employer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "dismiss",
    "inputs": [
      {
        "name": "employee",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "hasRequested",
    "inputs": [
      {
        "name": "employer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "employee",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingFor",
    "inputs": [
      {
        "name": "employer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "requestToJoin",
    "inputs": [
      {
        "name": "employer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "JoinRequestCancelled",
    "inputs": [
      {
        "name": "employer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "employee",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "JoinRequestDismissed",
    "inputs": [
      {
        "name": "employer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "employee",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "JoinRequested",
    "inputs": [
      {
        "name": "employer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "employee",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "JoinRequests__AlreadyRequested",
    "inputs": []
  },
  {
    "type": "error",
    "name": "JoinRequests__NoRequest",
    "inputs": []
  },
  {
    "type": "error",
    "name": "JoinRequests__NotAnEmployer",
    "inputs": []
  },
  {
    "type": "error",
    "name": "JoinRequests__SelfRequest",
    "inputs": []
  },
  {
    "type": "error",
    "name": "JoinRequests__TooManyRequests",
    "inputs": []
  },
  {
    "type": "error",
    "name": "JoinRequests__ZeroAddress",
    "inputs": []
  }
] as const;
