#!/usr/bin/env bash
# Copies contract ABIs and deployed addresses into frontend/lib/contracts/.
# ABIs become `export const XAbi = [...] as const` so viem infers types.
# Addresses come from every deployments/<chainId>.json, keyed by chain id.
# Run after `forge build` and after every deploy.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
shopt -s nullglob
DEPLOYMENTS=("$ROOT"/deployments/*.json)
OUT="$ROOT/frontend/lib/contracts"
mkdir -p "$OUT/abis"

CONTRACTS=(
  DayzePayroll
  ApprovalPolicy
  AuditRegistry
  HumanRegistry
  IncomeCredential
  JoinRequests
  ConfidentialToken
  ConfidentialNative
  ERC20_Harness
)

for name in "${CONTRACTS[@]}"; do
  artifact="$ROOT/out/$name.sol/$name.json"
  if [[ ! -f "$artifact" ]]; then
    echo "missing $artifact; run forge build" >&2
    exit 1
  fi
  {
    echo "// Generated by script/export-abis.sh. Do not edit."
    printf 'export const %sAbi = %s as const;\n' "$name" "$(jq '.abi' "$artifact")"
  } > "$OUT/abis/$name.ts"
done

{
  echo "// Generated by script/export-abis.sh. Do not edit."
  for name in "${CONTRACTS[@]}"; do
    echo "export { ${name}Abi } from \"./$name\";"
  done
} > "$OUT/abis/index.ts"

{
  echo "// Generated by script/export-abis.sh. Do not edit."
  echo "// Keyed by chain id: 421614 = Arbitrum Sepolia, 84532 = Base Sepolia."
  if (( ${#DEPLOYMENTS[@]} == 0 )); then
    json="{}"
  else
    json="$(jq -s 'map({(.chainId | tostring): (del(.chainId))}) | add' "${DEPLOYMENTS[@]}")"
  fi
  printf 'export const addresses = %s as const;\n' "$json"
  echo
  echo "export type SupportedChainId = keyof typeof addresses;"
} > "$OUT/addresses.ts"

echo "Exported ${#CONTRACTS[@]} ABIs and ${#DEPLOYMENTS[@]} deployment(s) to frontend/lib/contracts/"
