// Generated by script/export-abis.sh. Do not edit.
// Keyed by chain id: 421614 = Arbitrum Sepolia, 84532 = Base Sepolia.
export const addresses = {} as const;

export type SupportedChainId = keyof typeof addresses;
