// Generated by script/export-abis.sh. Do not edit.
// Keyed by chain id: 84532 = Base Sepolia.
export const addresses = {
  "84532": {
    "approvalPolicy": "0x3d2B7DF01ac8D8aB729E4998FC4BcDb02436Ba78",
    "arb": "0x551904f44630B7C2ac9BBf81db795928Cc329E86",
    "auditRegistry": "0x8529e281E8dB02fBE76a3ebe85a909b5eAbaAf77",
    "carb": "0x12F9FF86633d0633cB91c7992018f503ab2dfEd6",
    "ceth": "0x213d51712c33C0e449E02e3A47aCd75634231454",
    "cusdc": "0xbEDdCB7B043BbF075264C8E642f1161E1c58726B",
    "deployBlock": 47880944,
    "humanRegistry": "0xfC2b497D63a68ED186f7D2BdE49Ad7c9C2Dd6B20",
    "incomeCredential": "0x34635634F32127c4A51E74eE3e0E3B223a13d80E",
    "joinRequests": "0xc356dA49AeF6D7C486d3e3b1456fb7880a21Cf4b",
    "payroll": "0x11Be620B96a5516ad46CbFB8D1a25c5a67E8211F",
    "period": 600,
    "usdc": "0xce0c01B9c2E407af328eB25D06aea0f1929aaBC7"
  }
} as const;

export type SupportedChainId = keyof typeof addresses;
