// Generated by script/export-abis.sh. Do not edit.
// Keyed by chain id: 421614 = Arbitrum Sepolia, 84532 = Base Sepolia.
export const addresses = {
  "421614": {
    "approvalPolicy": "0xbBcd4f9479d01cf3dAf030250dDc84672bE6C492",
    "arb": "0xc356dA49AeF6D7C486d3e3b1456fb7880a21Cf4b",
    "auditRegistry": "0x5C26af9904a73087DF915852c4F8222c77c90Ca7",
    "carb": "0xE20c9348A93B308E7eBc914f34DCf30dc3e56bf0",
    "ceth": "0x350784A9f4DD60b80102A3C7665357851A3f1cfD",
    "cusdc": "0xc65998771586F40b93DB36cc5F8269A001A3534a",
    "deployBlock": 11869452,
    "humanRegistry": "0x953AD9dC75e355660e28b3FDA5307E588e9a95D0",
    "incomeCredential": "0xe2e044CBDA704A5F6e0de3A84061101d7bb127E3",
    "payroll": "0x1F69D46D2eA5bCC08A2690406133257fAd63ae27",
    "period": 600,
    "usdc": "0x34635634F32127c4A51E74eE3e0E3B223a13d80E"
  }
} as const;

export type SupportedChainId = keyof typeof addresses;
